/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ImpactRouteImport } from './routes/impact'
import { Route as PartnerRouteImport } from './routes/partner'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TransparencyRouteImport } from './routes/transparency'
import { Route as VolunteerRouteImport } from './routes/volunteer'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminDocumentsRouteImport } from './routes/admin.documents'
import { Route as AdminDonationsRouteImport } from './routes/admin.donations'
import { Route as AdminEventsRouteImport } from './routes/admin.events'
import { Route as AdminMessagesRouteImport } from './routes/admin.messages'
import { Route as AdminMetricsRouteImport } from './routes/admin.metrics'
import { Route as AdminPartnersRouteImport } from './routes/admin.partners'
import { Route as AdminVolunteersRouteImport } from './routes/admin.volunteers'
import { Route as PoliciesSlugRouteImport } from './routes/policies.$slug'
import { Route as WorkIndexRouteImport } from './routes/work.index'
import { Route as WorkSlugRouteImport } from './routes/work.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactRoute = ImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRoute = PartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TransparencyRoute = TransparencyRouteImport.update({
  id: '/transparency',
  path: '/transparency',
  getParentRoute: () => rootRouteImport,
} as any)
const VolunteerRoute = VolunteerRouteImport.update({
  id: '/volunteer',
  path: '/volunteer',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDocumentsRoute = AdminDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDonationsRoute = AdminDonationsRouteImport.update({
  id: '/donations',
  path: '/donations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMetricsRoute = AdminMetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPartnersRoute = AdminPartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVolunteersRoute = AdminVolunteersRouteImport.update({
  id: '/volunteers',
  path: '/volunteers',
  getParentRoute: () => AdminRoute,
} as any)
const PoliciesSlugRoute = PoliciesSlugRouteImport.update({
  id: '/policies/$slug',
  path: '/policies/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkIndexRoute = WorkIndexRouteImport.update({
  id: '/work/',
  path: '/work/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkSlugRoute = WorkSlugRouteImport.update({
  id: '/work/$slug',
  path: '/work/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/events': typeof EventsRoute
  '/impact': typeof ImpactRoute
  '/partner': typeof PartnerRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/transparency': typeof TransparencyRoute
  '/volunteer': typeof VolunteerRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/donations': typeof AdminDonationsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/metrics': typeof AdminMetricsRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/admin/volunteers': typeof AdminVolunteersRoute
  '/policies/$slug': typeof PoliciesSlugRoute
  '/work/$slug': typeof WorkSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/work/': typeof WorkIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/events': typeof EventsRoute
  '/impact': typeof ImpactRoute
  '/partner': typeof PartnerRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/transparency': typeof TransparencyRoute
  '/volunteer': typeof VolunteerRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/donations': typeof AdminDonationsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/metrics': typeof AdminMetricsRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/admin/volunteers': typeof AdminVolunteersRoute
  '/policies/$slug': typeof PoliciesSlugRoute
  '/work/$slug': typeof WorkSlugRoute
  '/admin': typeof AdminIndexRoute
  '/work': typeof WorkIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/events': typeof EventsRoute
  '/impact': typeof ImpactRoute
  '/partner': typeof PartnerRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/transparency': typeof TransparencyRoute
  '/volunteer': typeof VolunteerRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/donations': typeof AdminDonationsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/metrics': typeof AdminMetricsRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/admin/volunteers': typeof AdminVolunteersRoute
  '/policies/$slug': typeof PoliciesSlugRoute
  '/work/$slug': typeof WorkSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/work/': typeof WorkIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/donate'
    | '/events'
    | '/impact'
    | '/partner'
    | '/sitemap.xml'
    | '/transparency'
    | '/volunteer'
    | '/admin/documents'
    | '/admin/donations'
    | '/admin/events'
    | '/admin/messages'
    | '/admin/metrics'
    | '/admin/partners'
    | '/admin/volunteers'
    | '/policies/$slug'
    | '/work/$slug'
    | '/admin/'
    | '/work/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/donate'
    | '/events'
    | '/impact'
    | '/partner'
    | '/sitemap.xml'
    | '/transparency'
    | '/volunteer'
    | '/admin/documents'
    | '/admin/donations'
    | '/admin/events'
    | '/admin/messages'
    | '/admin/metrics'
    | '/admin/partners'
    | '/admin/volunteers'
    | '/policies/$slug'
    | '/work/$slug'
    | '/admin'
    | '/work'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/donate'
    | '/events'
    | '/impact'
    | '/partner'
    | '/sitemap.xml'
    | '/transparency'
    | '/volunteer'
    | '/admin/documents'
    | '/admin/donations'
    | '/admin/events'
    | '/admin/messages'
    | '/admin/metrics'
    | '/admin/partners'
    | '/admin/volunteers'
    | '/policies/$slug'
    | '/work/$slug'
    | '/admin/'
    | '/work/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  DonateRoute: typeof DonateRoute
  EventsRoute: typeof EventsRoute
  ImpactRoute: typeof ImpactRoute
  PartnerRoute: typeof PartnerRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TransparencyRoute: typeof TransparencyRoute
  VolunteerRoute: typeof VolunteerRoute
  PoliciesSlugRoute: typeof PoliciesSlugRoute
  WorkSlugRoute: typeof WorkSlugRoute
  WorkIndexRoute: typeof WorkIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact': {
      id: '/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof ImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner': {
      id: '/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof PartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transparency': {
      id: '/transparency'
      path: '/transparency'
      fullPath: '/transparency'
      preLoaderRoute: typeof TransparencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volunteer': {
      id: '/volunteer'
      path: '/volunteer'
      fullPath: '/volunteer'
      preLoaderRoute: typeof VolunteerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/documents': {
      id: '/admin/documents'
      path: '/documents'
      fullPath: '/admin/documents'
      preLoaderRoute: typeof AdminDocumentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/donations': {
      id: '/admin/donations'
      path: '/donations'
      fullPath: '/admin/donations'
      preLoaderRoute: typeof AdminDonationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/metrics': {
      id: '/admin/metrics'
      path: '/metrics'
      fullPath: '/admin/metrics'
      preLoaderRoute: typeof AdminMetricsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/partners': {
      id: '/admin/partners'
      path: '/partners'
      fullPath: '/admin/partners'
      preLoaderRoute: typeof AdminPartnersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/volunteers': {
      id: '/admin/volunteers'
      path: '/volunteers'
      fullPath: '/admin/volunteers'
      preLoaderRoute: typeof AdminVolunteersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/policies/$slug': {
      id: '/policies/$slug'
      path: '/policies/$slug'
      fullPath: '/policies/$slug'
      preLoaderRoute: typeof PoliciesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/': {
      id: '/work/'
      path: '/work'
      fullPath: '/work/'
      preLoaderRoute: typeof WorkIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/$slug': {
      id: '/work/$slug'
      path: '/work/$slug'
      fullPath: '/work/$slug'
      preLoaderRoute: typeof WorkSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminDocumentsRoute: typeof AdminDocumentsRoute
  AdminDonationsRoute: typeof AdminDonationsRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminMetricsRoute: typeof AdminMetricsRoute
  AdminPartnersRoute: typeof AdminPartnersRoute
  AdminVolunteersRoute: typeof AdminVolunteersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDocumentsRoute: AdminDocumentsRoute,
  AdminDonationsRoute: AdminDonationsRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminMetricsRoute: AdminMetricsRoute,
  AdminPartnersRoute: AdminPartnersRoute,
  AdminVolunteersRoute: AdminVolunteersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  DonateRoute: DonateRoute,
  EventsRoute: EventsRoute,
  ImpactRoute: ImpactRoute,
  PartnerRoute: PartnerRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TransparencyRoute: TransparencyRoute,
  VolunteerRoute: VolunteerRoute,
  PoliciesSlugRoute: PoliciesSlugRoute,
  WorkSlugRoute: WorkSlugRoute,
  WorkIndexRoute: WorkIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
